apiVersion: v1
kind: Service
metadata:
  name: healthcare-api
  namespace: healthcare
  labels:
    app: healthcare-api
  annotations:
    # Expose Prometheus metrics to ServiceMonitor
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: healthcare-api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
