apiVersion: v1
kind: ServiceAccount
metadata:
  name: healthcare-api
  namespace: healthcare
  labels:
    app: healthcare-api
  annotations:
    # IRSA — replace with the IAM role ARN created by Terraform (EKS module)
    # eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/healthcare-api-role
